seed = 0

[data]
normalization = 'quantile'
path = 'data/bleve'
y_policy = 'mean_std'

[model]
d_layers = [ 256, 256, 256]
dropout = 0.1

[training]
batch_size = 512
eval_batch_size = 256
lr = 0.1
n_epochs = 1000000000
optimizer = 'adamw'
patience = 16
weight_decay = 0.0001516844843295177
